Numpy:

- numpy.array(object, dtype=None, \*, copy=True, order='K', subok=False, ndmin=0, like=None)
- numpy.ndarray.flat[]
- numpy.ndarray.flatten
- numpy.ndarray.T
- numpy.delete(arr, obj, axis=0) # 0:row; 1:column
- np.copy
- copy.deepcopy()
- numpy.repeat(a, repeats, axis=None)
- numpy.tile(A, reps)
- numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None, \*, equal_nan=True)
- numpy.ravel(a, order='C')
- Indexing and Slicing

_Link:https://numpy.org/doc/stable/reference/generated/numpy.array.html_ <br/>
_Link: https://numpy.org/doc/stable/reference/_


_================================== Importing the required Libraries ===========================_


In [16]:
import numpy as np
import copy

In [17]:
A = np.array([[1, 8], [9, 15], [5, 6]])
A.flat[3]

15

In [18]:
A.flatten()

array([ 1,  8,  9, 15,  5,  6])

In [19]:
A.T

array([[ 1,  9,  5],
       [ 8, 15,  6]])

In [5]:
np.delete(A, 2, axis=0)

array([[ 1,  8],
       [ 9, 15]])

In [46]:
b = np.copy(A)
b[2][0] = 10
print(f"A:\n {A},\n b:\n {b}")

A:
 [[ 1  8]
 [ 9 15]
 [ 5  6]],
 b:
 [[ 1  8]
 [ 9 15]
 [10  6]]


In [45]:
c = copy.deepcopy(A)
c[2][0] = 12
print(f"A:\n {A},\n c:\n {c}")

A:
 [[ 1  8]
 [ 9 15]
 [ 5  6]],
 c:
 [[ 1  8]
 [ 9 15]
 [12  6]]


In [43]:
print(f"A:\n {A}")
print(f"Repeat_Row:\n {np.repeat(A,2,axis=0)}")
print(f"Repeat_Column:\n {np.repeat(A,2,axis=1)}")
a = np.repeat(A, [3, 1], axis=1)
print(f"Repetition rate of the first column, Repetition rate of the second column: \n{a}")

A:
 [[ 1  8]
 [ 9 15]
 [ 5  6]]
Repeat_Row:
 [[ 1  8]
 [ 1  8]
 [ 9 15]
 [ 9 15]
 [ 5  6]
 [ 5  6]]
Repeat_Column:
 [[ 1  1  8  8]
 [ 9  9 15 15]
 [ 5  5  6  6]]
Repetition rate of the first column, Repetition rate of the second column: 
[[ 1  1  1  8]
 [ 9  9  9 15]
 [ 5  5  5  6]]


In [47]:
print(f"A:\n {A}")
np.tile(A, (2, 2))

A:
 [[ 1  8]
 [ 9 15]
 [ 5  6]]


array([[ 1,  8,  1,  8],
       [ 9, 15,  9, 15],
       [ 5,  6,  5,  6],
       [ 1,  8,  1,  8],
       [ 9, 15,  9, 15],
       [ 5,  6,  5,  6]])

In [22]:
B = np.array([[1, 1, 2, 5, 5], [5, 4, 5, 5, 6], [7, 9, 8, 8, 9]])
np.unique(B)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [48]:
print(f"A:\n {A}")
print(f"np.ravel: {np.ravel(A,order='A')}")
print(f"np.ravel: {np.ravel(A,order='F')}")

A:
 [[ 1  8]
 [ 9 15]
 [ 5  6]]
np.ravel: [ 1  8  9 15  5  6]
np.ravel: [ 1  9  5  8 15  6]


In [33]:
B=np.array([1,2,3,4,5,6,7,8,9])
BB=B[1:4]  
print(f"B[1:4] or BB: {BB}") 
BB[0:2]=12 
print(f"BB: {BB}")    
print(f"B: {B}")

B[1:4] or BB: [2 3 4]
BB: [12 12  4]
B: [ 1 12 12  4  5  6  7  8  9]


In [49]:
print(f"A:\n {A}")
print(f"A[1]: {A[1]}")
print(f"A[1][1] or A[1,1]: {A[1][1]}")

A:
 [[ 1  8]
 [ 9 15]
 [ 5  6]]
A[1]: [ 9 15]
A[1][1] or A[1,1]: 15


In [62]:
B=np.array([[1,2,3],[4,5,6]])
print(f"B is 2-D(2*3): \n {B}")
C=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"C is 3-D(2*2*3): \n {C}")
print(f"C[0]:\n {C[0]} \n C[1]:\n{C[1]}")
print(f"C[0][1] or C[0,1]:\n {C[0][1]} \n C[1][1] or C[1,1]:\n{C[1][1]}")
C[0]=100
print(f"C[0]=100:\n {C[0]} ")

B is 2-D(2*3): 
 [[1 2 3]
 [4 5 6]]
C is 3-D(2*2*3): 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
C[0]:
 [[1 2 3]
 [4 5 6]] 
 C[1]:
[[ 7  8  9]
 [10 11 12]]
C[0][1] or C[0,1]:
 [4 5 6] 
 C[1][1] or C[1,1]:
[10 11 12]
C[0]=100:
 [[100 100 100]
 [100 100 100]] 


In [65]:
B=np.array([[1,2,3],[4,5,6]])
B[:2,1:]                     # [row i:row j, col i:col j]

array([[2, 3],
       [5, 6]])